# -*- coding: utf-8 -*-
"""SPM1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FOp-Hnag0n2il7zvgPXv7bqvPNjYddz
"""

import numpy as np
from numpy import pi, sqrt, sin, cos, exp, log10, array, real, conj

import matplotlib
# matplotlib.rcParams['text.usetex'] = True
from matplotlib import pyplot as plt
from scipy import interpolate
#import seaborn as sns
# %matplotlib inline
import pandas as pd
import glob

#sns.set()

## Parámetros Globales ##

#onda incidente
def kiz(k0,thi): 
    return k0*cos(thi)

def kix(k0,thi,phi):
    return k0*sin(thi)*cos(phi)

def kiy(k0,thi,phi):
    return k0*sin(thi)*sin(phi)

def kir(k0,thi):
    return k0*sin(thi)

#onda dispersada
def kx(k0,th,ph):
    return k0*sin(th)*cos(ph)

def ky(k0,th,ph):
    return k0*sin(th)*sin(ph)

def k0z(k0,th):
    return k0*cos(th)
    
#ondas transmitidas
def k1z(k0,th,ep1):
    return k0*sqrt(ep1-sin(th)**2)

def k2z(k0,th,ep2):
    return k0*sqrt(ep2-sin(th)**2)

##kz interface plana

def k1zi(k0,thi,ep1):
    return k0*sqrt(ep1-sin(thi)**2)

def k2zi(k0,thi,ep2):
    return k0*sqrt(ep2-sin(thi)**2)

#componente tangencial
def kr(k0,th):
    return k0*sin(th)

#-------------------------------------------#

"""<h1>AMPLITUDES DE LAS ONDAS DISPERSADAS/TRANSMITIDAS </h1>
<br>
<br>

**Coeficientes a: asociados a las ondas dispersadas en +z en la region 0**
<br>
<br>

**coeficientes bb: asociados a las ondas dispersadas en +z en la region 1**
<br>
<br>

**coeficientes b: asociados a las ondas dispersadas en -z en la region 1**
<br>
<br>

**coeficientes c: asociados a las ondas dispersadas en -z en la region 2**

<h2> Coeficientes de orden cero </h2>
"""

## CANAL HH ##

def a0HH(k0,thi,ep1,ep2,d):
    return (-1j*k1zi(k0,thi,ep1)*(k2zi(k0,thi,ep2) - kiz(k0,thi))*cos(d*k1zi(k0,thi,ep1)) + (-k1zi(k0,thi,ep1)**2 + k2zi(k0,thi,ep2)*kiz(k0,thi))*sin(d*k1zi(k0,thi,ep1)))/(1j*k1zi(k0,thi,ep1)*(k2zi(k0,thi,ep2) + kiz(k0,thi))*cos(d*k1zi(k0,thi,ep1)) + (k1zi(k0,thi,ep1)**2 + k2zi(k0,thi,ep2)*kiz(k0,thi))*sin(d*k1zi(k0,thi,ep1)))

def bb0HH(k0,thi,ep1,ep2,d):
    return (2*kiz(k0,thi))/(-k1zi(k0,thi,ep1) + kiz(k0,thi) + ((k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2))*(k1zi(k0,thi,ep1) + kiz(k0,thi)))/(exp(2*1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1) - k2zi(k0,thi,ep2))))

def b0HH(k0,thi,ep1,ep2,d):
    return (-2*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2))*kiz(k0,thi))/(exp(2*1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1) - k2zi(k0,thi,ep2))*(k1zi(k0,thi,ep1) - kiz(k0,thi)) - (k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2))*(k1zi(k0,thi,ep1) + kiz(k0,thi)))

def c0HH(k0,thi,ep1,ep2,d):
    return (-4*exp(1j*d*(k1zi(k0,thi,ep1) - k2zi(k0,thi,ep2)))*k1zi(k0,thi,ep1)*kiz(k0,thi))/(exp(2*1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1) - k2zi(k0,thi,ep2))*(k1zi(k0,thi,ep1) - kiz(k0,thi)) - (k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2))*(k1zi(k0,thi,ep1) + kiz(k0,thi)))

## CANAL VH ##

a0VH = 0
bb0VH = 0
b0VH = 0
c0VH = 0

## CANAL VV ##
def a0VV(k0,thi,ep1,ep2,d):
    return (-1j*k1zi(k0,thi,ep1)*ep1*(k2zi(k0,thi,ep2) - kiz(k0,thi)*ep2)*cos(d*k1zi(k0,thi,ep1)) + (k2zi(k0,thi,ep2)*kiz(k0,thi)*ep1**2 - k1zi(k0,thi,ep1)**2*ep2)*sin(d*k1zi(k0,thi,ep1)))/(1j*k1zi(k0,thi,ep1)*ep1*(k2zi(k0,thi,ep2) + kiz(k0,thi)*ep2)*cos(d*k1zi(k0,thi,ep1)) + (k2zi(k0,thi,ep2)*kiz(k0,thi)*ep1**2 + k1zi(k0,thi,ep1)**2*ep2)*sin(d*k1zi(k0,thi,ep1)))

def bb0VV(k0,thi,ep1,ep2,d):
    return (2*exp(2*1j*d*k1zi(k0,thi,ep1))*kiz(k0,thi)*sqrt(ep1)*(k2zi(k0,thi,ep2)*ep1 - k1zi(k0,thi,ep1)*ep2))/(exp(2*1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1) - kiz(k0,thi)*ep1)*(-(k2zi(k0,thi,ep2)*ep1) + k1zi(k0,thi,ep1)*ep2) - (k1zi(k0,thi,ep1) + kiz(k0,thi)*ep1)*(k2zi(k0,thi,ep2)*ep1 + k1zi(k0,thi,ep1)*ep2))


def b0VV(k0,thi,ep1,ep2,d):
    return (-2*kiz(k0,thi)*sqrt(ep1)*(k2zi(k0,thi,ep2)*ep1 + k1zi(k0,thi,ep1)*ep2))/(exp(2*1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1) - kiz(k0,thi)*ep1)*(-(k2zi(k0,thi,ep2)*ep1) + k1zi(k0,thi,ep1)*ep2) - (k1zi(k0,thi,ep1) + kiz(k0,thi)*ep1)*(k2zi(k0,thi,ep2)*ep1 + k1zi(k0,thi,ep1)*ep2))

def c0VV(k0,thi,ep1,ep2,d):
    return (-4*exp(1j*d*(k1zi(k0,thi,ep1) - k2zi(k0,thi,ep2)))*k1zi(k0,thi,ep1)*kiz(k0,thi)*ep1*sqrt(ep2))/(exp(2*1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1) - kiz(k0,thi)*ep1)*(-(k2zi(k0,thi,ep2)*ep1) + k1zi(k0,thi,ep1)*ep2) - (k1zi(k0,thi,ep1) + kiz(k0,thi)*ep1)*(k2zi(k0,thi,ep2)*ep1 + k1zi(k0,thi,ep1)*ep2))

## CANAL HV ##

a0HV = 0
bb0HV = 0
b0HV = 0
c0HV = 0

"""<h2> Coeficientes de orden uno </h2>
<br>
<br>

**Coeficientes aF1: asociados a las ondas dispersadas en +z en la region 0 y proporcionales
a el espectro de rugosisdad de la primera capa**
<br>
<br>

**Coeficientes aF2: asociados a las ondas dispersadas en +z en la region 0 y proporcionales
a el espectro de rugosisdad de la segunda capa**
<br>
<br>

**Lo mismo vale para los coeficientes 'bb', 'b' y 'c'**
"""

## CANAL HH ##
# AMPLITUD ONDA DISPERSADA #
def a1HHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return ((kr(k0,th)*((1 + a0HH(k0,thi,ep1,ep2,d))*exp(1j*d*(2*k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*sqrt(ep1)*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) - k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))-\
            exp(1j*d*(2*k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*((-1 + a0HH(k0,thi,ep1,ep2,d))*k1z(k0,th,ep1)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + bb0HH(k0,thi,ep1,ep2,d)*(k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))) + \
            b0HH(k0,thi,ep1,ep2,d)*(k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))))*sqrt(ep1)*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) - k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) + \
            exp(1j*d*k1zi(k0,thi,ep1))*((1 + a0HH(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*sqrt(ep1) - \
            (-((-1 + a0HH(k0,thi,ep1,ep2,d))*k1z(k0,th,ep1)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + bb0HH(k0,thi,ep1,ep2,d)*(k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))) + \
            b0HH(k0,thi,ep1,ep2,d)*(-(k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))))*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(k0z(k0,th)*sqrt(ep1)*((1 + exp(2*1j*d*k1z(k0,th,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) - (-1 + exp(2*1j*d*k1z(k0,th,ep1)))*k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) + \
            k1z(k0,th,ep1)*sqrt(ep1)*(-((-1 + exp(2*1j*d*k1z(k0,th,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + (1 + exp(2*1j*d*k1z(k0,th,ep1)))*k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))) 

def a1HHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(kr(k0,th)*(2*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) - k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) + \
            kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2)) + 2*bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*k1z(k0,th,ep1)*sqrt(ep1)*\
            (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) + k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) + kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2)) - \
            2*c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*k1z(k0,th,ep1)*(-(k2z(k0,th,ep2)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(kix(k0,thi,phi)*kx(k0,th,ph) - kx(k0,th,ph)**2 + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep1*sqrt(ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(k0z(k0,th)*sqrt(ep1)*((1 + exp(2*1j*d*k1z(k0,th,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) - (-1 + exp(2*1j*d*k1z(k0,th,ep1)))*k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) + \
            k1z(k0,th,ep1)*sqrt(ep1)*(-((-1 + exp(2*1j*d*k1z(k0,th,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + (1 + exp(2*1j*d*k1z(k0,th,ep1)))*k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))

# COEFICIENTES AUXILIARES CANAL HH #
def bb1HHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return (exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*kr(k0,th)*(-(exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*((-1 + a0HH(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - (1 + a0HH(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2)))*sqrt(ep1)*\
            (k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) - k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))) - bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*\
            (k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) - (k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) + \
            b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*\
            (-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))/\
            (kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - \
            (k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))  
 
def bb1HHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return (exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*kr(k0,th)*(-(b0HH(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1zi(k0,thi,ep1))*(k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*\
            (k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) - (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1)*sqrt(ep2))) + \
            bb0HH(k0,thi,ep1,ep2,d)*(k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1)*sqrt(ep2)) + \
            c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(k2z(k0,th,ep2)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(-(kix(k0,thi,phi)*kx(k0,th,ph)) + kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*(k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*sqrt(ep1)*sqrt(ep2)))/\
            (kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - \
            (k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))     

def b1HHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return (kr(k0,th)*(bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) - (k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*\
            (k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*\
            (k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - \
            exp(1j*d*k1zi(k0,thi,ep1))*((-1 + a0HH(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - (1 + a0HH(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2)))*sqrt(ep1)*\
            (k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - \
            (k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)))) 

def b1HHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return (kr(k0,th)*(b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) - \
            (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1)*sqrt(ep2)) - \
            bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)*sqrt(ep2) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1)*sqrt(ep2)) + \
            c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(-(k2z(k0,th,ep2)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*sqrt(ep1)*sqrt(ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - \
            (k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))

def c1HHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return (kr(k0,th)*(-2*bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(-(k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1)) + (k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*sqrt(ep1)*sqrt(ep2) + \
            2*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(-((-1 + a0HH(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + (1 + a0HH(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2)))*ep1*sqrt(ep2) - \
            2*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*sqrt(ep1)*sqrt(ep2)*cos(d*k1zi(k0,thi,ep1)) + \
            2*1j*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*sqrt(ep1)*sqrt(ep2)*sin(d*k1zi(k0,thi,ep1))))/\
            (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - \
            (k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))

def c1HHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return (kr(k0,th)*(bb0HH(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*(-(k0z(k0,th)*sqrt(ep1)) + k1z(k0,th,ep1)*sqrt(ep1))*sqrt(ep1)*sqrt(ep2) - \
            bb0HH(k0,thi,ep1,ep2,d)*(k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(-(kix(k0,thi,phi)*kx(k0,th,ph)) + kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*(k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*sqrt(ep1)*sqrt(ep2) + \
            2*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*sqrt(ep1)*sqrt(ep2)*cos(d*k1z(k0,th,ep1)) - \
            2*1j*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*(k1z(k0,th,ep1)**2*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + k0z(k0,th)*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1))*sqrt(ep1)*sqrt(ep2)*\
            sin(d*k1z(k0,th,ep1)) + 2*1j*c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(1j*k1z(k0,th,ep1)*ep1*(k0z(k0,th)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep2) + (k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep2))*\
            cos(d*k1z(k0,th,ep1)) + (k1z(k0,th,ep1)**2*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1*sqrt(ep2) + k0z(k0,th)*(k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep1*sqrt(ep2))*sin(d*k1z(k0,th,ep1)))))/\
            (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th)*sqrt(ep1) - k1z(k0,th,ep1)*sqrt(ep1))*(-(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2)) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2)) - 
            (k0z(k0,th)*sqrt(ep1) + k1z(k0,th,ep1)*sqrt(ep1))*(k1z(k0,th,ep1)*sqrt(ep1)*sqrt(ep2) + k2z(k0,th,ep2)*sqrt(ep1)*sqrt(ep2))))

## CANAL VH ##
# AMPLITUD ONDA DISPERSADA #
def a1VHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(exp(1j*d*(2*k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(-((1 + a0HH(k0,thi,ep1,ep2,d))*k1z(k0,th,ep1)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*sqrt(ep1)) + k1z(k0,th,ep1)*(bb0HH(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1)**2 + b0HH(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1)**2 + (bb0HH(k0,thi,ep1,ep2,d) + b0HH(k0,thi,ep1,ep2,d))*kir(k0,thi)**2)*sqrt(ep1) + \
            (-bb0HH(k0,thi,ep1,ep2,d) + b0HH(k0,thi,ep1,ep2,d))*k1zi(k0,thi,ep1) + (-1 + a0HH(k0,thi,ep1,ep2,d))*kiz(k0,thi))*ep1**1.5)*sqrt(ep2)*(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2) + \
            exp(1j*d*k1zi(k0,thi,ep1))*((1 + a0HH(k0,thi,ep1,ep2,d))*k1z(k0,th,ep1)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*sqrt(ep1) - k1z(k0,th,ep1)*(bb0HH(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1)**2 + b0HH(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1)**2 + (bb0HH(k0,thi,ep1,ep2,d) + b0HH(k0,thi,ep1,ep2,d))*kir(k0,thi)**2)*sqrt(ep1) + ((-bb0HH(k0,thi,ep1,ep2,d) + b0HH(k0,thi,ep1,ep2,d))*k1zi(k0,thi,ep1) + (-1 + a0HH(k0,thi,ep1,ep2,d))*kiz(k0,thi))*ep1**1.5)*sqrt(ep2)*\
            (k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))/(exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep1)*sqrt(ep2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(-(k2z(k0,th,ep2)*ep1) +\
            k1z(k0,th,ep1)*ep2) - (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 +k1z(k0,th,ep1)*ep2)))


def a1VHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(-2*c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*k1z(k0,th,ep1)*ep1**1.5*sqrt(ep2)*(k2z(k0,th,ep2)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2) - k2zi(k0,thi,ep2)*ep2) + \
            2*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*ep1*sqrt(ep2)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1) - k1zi(k0,thi,ep1)*sqrt(ep1)*ep2) + \
            2*bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*k1z(k0,th,ep1)*ep1*sqrt(ep2)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1) + k1zi(k0,thi,ep1)*sqrt(ep1)*ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep1)*sqrt(ep2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2) - (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))


# COEFICIENTES AUXILIARES CANAL VH #
def bb1VHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return (exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*(kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(k1zi(k0,thi,ep1)*sqrt(ep1) - k0z(k0,th)*(k1z(k0,th,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1))*sqrt(ep2)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + \
            b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(k1zi(k0,thi,ep1)*sqrt(ep1) + k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1))*sqrt(ep2)*(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2) + \
            exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*((-1 + a0HH(k0,thi,ep1,ep2,d))*kiz(k0,thi) - (1 + a0HH(k0,thi,ep1,ep2,d))*k0z(k0,th)*(kiz(k0,thi)**2 + kir(k0,thi)**2))*sqrt(ep1)*sqrt(ep2)*(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2)))/\
            (kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2))) 


def bb1VHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return (exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*(kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(-(c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*sqrt(ep1)*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*sqrt(ep2)*(k2z(k0,th,ep2)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2) - k2zi(k0,thi,ep2)*ep2)) + \
            b0HH(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1zi(k0,thi,ep1))*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*sqrt(ep2)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1) - k1zi(k0,thi,ep1)*sqrt(ep1)*ep2) + bb0HH(k0,thi,ep1,ep2,d)*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*sqrt(ep2)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1) + k1zi(k0,thi,ep1)*sqrt(ep1)*ep2)))/\
            (kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))

def b1VHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return  -(((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1)*sqrt(ep1) - k0z(k0,th)*(k1z(k0,th,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1))*sqrt(ep2)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2) - \
            b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1)*sqrt(ep1) + k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1))*sqrt(ep2)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2) - \
            exp(1j*d*k1zi(k0,thi,ep1))*((-1 + a0HH(k0,thi,ep1,ep2,d))*kiz(k0,thi) - (1 + a0HH(k0,thi,ep1,ep2,d))*k0z(k0,th)*(kiz(k0,thi)**2 + kir(k0,thi)**2))*sqrt(ep1)*sqrt(ep2)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))) 

def b1VHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(c0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*sqrt(ep1)*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*sqrt(ep2)*(k2z(k0,th,ep2)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2) - k2zi(k0,thi,ep2)*ep2) + \
            b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*sqrt(ep2)*(-(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1)) + k1zi(k0,thi,ep1)*sqrt(ep1)*ep2) - \
            bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*sqrt(ep2)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1) + k1zi(k0,thi,ep1)*sqrt(ep1)*ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))

def c1VHF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(-2*bb0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(-(k1zi(k0,thi,ep1)*sqrt(ep1)) + k0z(k0,th)*(k1z(k0,th,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1))*ep1*sqrt(ep2) - \
            2*b0HH(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)*sqrt(ep1) + k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)*sqrt(ep1))*ep1*sqrt(ep2) - \
            2*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*((-1 + a0HH(k0,thi,ep1,ep2,d))*kiz(k0,thi) - (1 + a0HH(k0,thi,ep1,ep2,d))*k0z(k0,th)*(kiz(k0,thi)**2 + kir(k0,thi)**2))*ep1**1.5*sqrt(ep2)))/\
            (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep1)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))) 

def c1VHF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(c0HH(k0,thi,ep1,ep2,d)*sqrt(ep1)*(exp(1j*d*(2*k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k1z(k0,th,ep1)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2)*sqrt(ep2) - k2zi(k0,thi,ep2)*ep1*sqrt(ep2)) - \
            exp(1j*d*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k1z(k0,th,ep1)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2)*sqrt(ep2) + k2zi(k0,thi,ep2)*ep1*sqrt(ep2))) - \
            b0HH(k0,thi,ep1,ep2,d)*exp(2*1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*sqrt(ep1)*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1zi(k0,thi,ep1)*ep1)*sqrt(ep2) + bb0HH(k0,thi,ep1,ep2,d)*sqrt(ep1)*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1zi(k0,thi,ep1)*ep1)*sqrt(ep2) + \
            bb0HH(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1z(k0,th,ep1))*sqrt(ep1)*(-k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + k1zi(k0,thi,ep1)*ep1)*sqrt(ep2) + b0HH(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1zi(k0,thi,ep1))*sqrt(ep1)*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + k1zi(k0,thi,ep1)*ep1)*sqrt(ep2)))/\
            (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep1)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))

## CANAL VV ##
# AMPLITUD ONDA DISPERSADA #
def a1VVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return (kr(k0,th)*(exp(1j*d*(2*k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(-(k1z(k0,th,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*((-1 + a0VV(k0,thi,ep1,ep2,d))*kiz(k0,thi) + b0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1)*sqrt(ep1))) + bb0VV(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) - \
            (bb0VV(k0,thi,ep1,ep2,d) + b0VV(k0,thi,ep1,ep2,d))*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1) + (1 + a0VV(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*ep1)\
            *(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2) - exp(1j*d*k1zi(k0,thi,ep1))*(-(k1z(k0,th,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*((-1 + a0VV(k0,thi,ep1,ep2,d))*kiz(k0,thi) + b0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1)*sqrt(ep1))) + bb0VV(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*sqrt(ep1) + \
            (bb0VV(k0,thi,ep1,ep2,d) + b0VV(k0,thi,ep1,ep2,d))*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1) - (1 + a0VV(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*ep1)\
            *(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))/(exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2) - (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2))) 

def a1VVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return (kr(k0,th)*(-2*c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*k1z(k0,th,ep1)*(-(k2z(k0,th,ep2)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep1*sqrt(ep2) + \
            2*b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(-(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1) + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep2 + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))*ep2) + \
            2*bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*k1z(k0,th,ep1)*sqrt(ep1)*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1 + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep2 + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))*ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(-(k2z(k0,th,ep2)*ep1) + k1z(k0,th,ep1)*ep2) - (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))

# COEFICIENTES AUXILIARES CANAL VV #
def bb1VVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*kr(k0,th)*(exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*((-1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - (1 + a0VV(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2)))*sqrt(ep1)*\
            (k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) - k0z(k0,th)*k1z(k0,th,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + \
            b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) + k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2)))/\
            (kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))) 

def bb1VVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*kr(k0,th)*(c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(k2z(k0,th,ep2)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(-(kix(k0,thi,phi)*kx(k0,th,ph)) + kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*sqrt(ep1)*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*\
            sqrt(ep2) - b0VV(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1zi(k0,thi,ep1))*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1 - (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep2) + \
            bb0VV(k0,thi,ep1,ep2,d)*(k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1 + (k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep2)))/\
            (kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))

def b1VVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return  -((kr(k0,th)*(-(exp(1j*d*k1zi(k0,thi,ep1))*((-1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - (1 + a0VV(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2)))*sqrt(ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2))-\
            bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) - k0z(k0,th)*k1z(k0,th,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2) -\
             b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) + k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))) 

def b1VVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(kr(k0,th)*(-(c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(-(k2z(k0,th,ep2)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*sqrt(ep1)*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*sqrt(ep2))+\
             b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(-(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1) + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep2 + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))*ep2) +\
             bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k1zi(k0,thi,ep1)*k2z(k0,th,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1 + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep2 + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph))*ep2)))/\
             (exp(1j*d*k1zi(k0,thi,ep1))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))\


def c1VVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(kr(k0,th)*(2*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*((-1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - (1 + a0VV(k0,thi,ep1,ep2,d))*(kix(k0,thi,phi)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*kx(k0,th,ph) + kiy(k0,thi,phi)*kiz(k0,thi)**2*ky(k0,th,ph) - kir(k0,thi)**2*(kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2)))*ep1*sqrt(ep2) - \
             2*bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(-(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))) + kir(k0,thi)**2*(-(kix(k0,thi,phi)*kx(k0,th,ph)) + kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2) + k0z(k0,th)*k1z(k0,th,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*sqrt(ep2) + \
             2*b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) + k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*sqrt(ep2)*cos(d*k1zi(k0,thi,ep1)) - \
             2*1j*b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) + k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*sqrt(ep2)*sin(d*k1zi(k0,thi,ep1))))/\
             (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))


def c1VVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return  (kr(k0,th)*(bb0VV(k0,thi,ep1,ep2,d)*sqrt(ep1)*(-(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)) + \
             (k1z(k0,th,ep1)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) - k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*(-(kix(k0,thi,phi)*kx(k0,th,ph)) + kx(k0,th,ph)**2 - kiy(k0,thi,phi)*ky(k0,th,ph) + ky(k0,th,ph)**2))*(k1z(k0,th,ep1) + k0z(k0,th)*ep1))*sqrt(ep2) - \
             2*b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) + k0z(k0,th)*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep1)*sqrt(ep2)*cos(d*k1z(k0,th,ep1)) + \
             2*1j*b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + 2*k1zi(k0,thi,ep1)))*sqrt(ep1)*(k1z(k0,th,ep1)**2*k1zi(k0,thi,ep1)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + k0z(k0,th)*(k1zi(k0,thi,ep1)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep1)*sqrt(ep2)*sin(d*k1z(k0,th,ep1)) + \
             2*c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(k1z(k0,th,ep1)*ep1*(k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)) + k0z(k0,th)*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep2)*cos(d*k1z(k0,th,ep1)) - \
             1j*(k0z(k0,th)*(k2zi(k0,thi,ep2)**2*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph)) + kir(k0,thi)**2*((kix(k0,thi,phi) - kx(k0,th,ph))*kx(k0,th,ph) + (kiy(k0,thi,phi) - ky(k0,th,ph))*ky(k0,th,ph)))*ep1**2 + k1z(k0,th,ep1)**2*k2zi(k0,thi,ep2)*(kix(k0,thi,phi)*kx(k0,th,ph) + kiy(k0,thi,phi)*ky(k0,th,ph))*ep2)*sin(d*k1z(k0,th,ep1)))))/\
            (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*(exp(2*1j*d*k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 - k1z(k0,th,ep1)*ep2) + (k1z(k0,th,ep1) + k0z(k0,th)*ep1)*(k2z(k0,th,ep2)*ep1 + k1z(k0,th,ep1)*ep2)))

## CANAL HV ##
# AMPLITUD ONDA DISPERSADA #
def a1HVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(2*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*ep1*(-((bb0VV(k0,thi,ep1,ep2,d) + b0VV(k0,thi,ep1,ep2,d))*k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)) + (kiz(k0,thi)*(-1 + a0VV(k0,thi,ep1,ep2,d) + (1 + a0VV(k0,thi,ep1,ep2,d))*k2z(k0,th,ep2)*kiz(k0,thi))+(1 + a0VV(k0,thi,ep1,ep2,d))*k2z(k0,th,ep2)*kir(k0,thi)**2)*sqrt(ep1) + \
            (-(bb0VV(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1)) + b0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1))*ep1)*sqrt(ep2)*cos(d*k1z(k0,th,ep1)) + 2*1j*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*ep1*\
            ((bb0VV(k0,thi,ep1,ep2,d)+b0VV(k0,thi,ep1,ep2,d))*k1z(k0,th,ep1)**2*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - ((-1 + a0VV(k0,thi,ep1,ep2,d))*k2z(k0,th,ep2)*kiz(k0,thi) + (1 + a0VV(k0,thi,ep1,ep2,d))*k1z(k0,th,ep1)**2*(kiz(k0,thi)**2 + kir(k0,thi)**2))*sqrt(ep1) + (bb0VV(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1) - b0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1))*k2z(k0,th,ep2)*ep1)*sqrt(ep2)*sin(d*k1z(k0,th,ep1))))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1**1.5*sqrt(ep2)))

def a1HVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(-2*c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*k1z(k0,th,ep1)*ep1**1.5*(k2z(k0,th,ep2)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2) - k2zi(k0,thi,ep2)*ep2) + \
            2*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*ep1*((bb0VV(k0,thi,ep1,ep2,d) + b0VV(k0,thi,ep1,ep2,d))*k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + (bb0VV(k0,thi,ep1,ep2,d) - b0VV(k0,thi,ep1,ep2,d))*k1zi(k0,thi,ep1)*ep1)*sqrt(ep2)*cos(d*k1zi(k0,thi,ep1)) - \
            2*1j*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*ep1*((bb0VV(k0,thi,ep1,ep2,d) - b0VV(k0,thi,ep1,ep2,d))*k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + (bb0VV(k0,thi,ep1,ep2,d) + b0VV(k0,thi,ep1,ep2,d))*k1zi(k0,thi,ep1)*ep1)*sqrt(ep2)*sin(d*k1zi(k0,thi,ep1))))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1**1.5*sqrt(ep2))

# COEFICIENTES AUXILIARES CANAL HV #

def bb1HVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)) + 1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(k1z(k0,th,ep1) - k2z(k0,th,ep2))*(kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*\
             ((bb0VV(k0,thi,ep1,ep2,d) + b0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + (-1 + a0VV(k0,thi,ep1,ep2,d))*kiz(k0,thi)*sqrt(ep1) - (1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*sqrt(ep1) + (-(bb0VV(k0,thi,ep1,ep2,d)*k1z(k0,th,ep1)) + b0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1))*ep1))/\
             ((exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*sqrt(ep1))) 

def bb1HVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(exp(1j*d*(k1z(k0,th,ep1) - k1zi(k0,thi,ep1)))*(kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*((k0z(k0,th) + k1z(k0,th,ep1))*sqrt(ep1)*(bb0VV(k0,thi,ep1,ep2,d)*k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + bb0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1)*ep1 + b0VV(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1zi(k0,thi,ep1))*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1zi(k0,thi,ep1)*ep1))*ep2 + \
            c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(k0z(k0,th) + k1z(k0,th,ep1))*ep1*sqrt(ep2)*(-(k2z(k0,th,ep2)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2)) + k2zi(k0,thi,ep2)*ep2)))/((exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1*ep2)

def b1HVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return -(((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(-(exp(1j*d*k1zi(k0,thi,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2))*(kiz(k0,thi)*(1 - a0VV(k0,thi,ep1,ep2,d) + (1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*kiz(k0,thi)) + (1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*kir(k0,thi)**2)*ep1*ep2) + \
            bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2))*sqrt(ep1)*(k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1z(k0,th,ep1)*ep1)*ep2 + b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2))*sqrt(ep1)*(k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + k1zi(k0,thi,ep1)*ep1)*ep2))/\
            (exp(1j*d*k1zi(k0,thi,ep1))*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1*ep2)) 

def b1HVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return -((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(b0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1zi(k0,thi,ep1) + 1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(-k0z(k0,th) + k1z(k0,th,ep1))*sqrt(ep1)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1zi(k0,thi,ep1)*ep1)*ep2 + \
             bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*k1z(k0,th,ep1))*(-k0z(k0,th) + k1z(k0,th,ep1))*sqrt(ep1)*(k2z(k0,th,ep2)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + k1zi(k0,thi,ep1)*ep1)*ep2 + c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*(-k0z(k0,th) + k1z(k0,th,ep1))*ep1*sqrt(ep2)*(-(k2z(k0,th,ep2)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2)) + k2zi(k0,thi,ep2)*ep2)))/\
             (exp(1j*d*k1zi(k0,thi,ep1))*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1*ep2)

def c1HVF1(k0,thi,phi,th,ph,ep1,ep2,d):
    return ((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(2*bb0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(-(k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2)) + k1z(k0,th,ep1)*ep1)*sqrt(ep2) - \
            2*exp(1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*k1z(k0,th,ep1)*sqrt(ep1)*(b0VV(k0,thi,ep1,ep2,d)*k0z(k0,th)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + (-1 + a0VV(k0,thi,ep1,ep2,d))*kiz(k0,thi)*sqrt(ep1) - (1 + a0VV(k0,thi,ep1,ep2,d))*k0z(k0,th)*(kiz(k0,thi)**2 + kir(k0,thi)**2)*sqrt(ep1) + b0VV(k0,thi,ep1,ep2,d)*k1zi(k0,thi,ep1)*ep1)*sqrt(ep2)))/\
            (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1*sqrt(ep2)) 

def c1HVF2(k0,thi,phi,th,ph,ep1,ep2,d):
    return 	((kiy(k0,thi,phi)*kx(k0,th,ph) - kix(k0,thi,phi)*ky(k0,th,ph))*kr(k0,th)*(-(b0VV(k0,thi,ep1,ep2,d)*exp(2*1j*d*(k1z(k0,th,ep1) + k1zi(k0,thi,ep1)))*(-k0z(k0,th) + k1z(k0,th,ep1))*sqrt(ep1)*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1zi(k0,thi,ep1)*ep1)*sqrt(ep2)) + \
             b0VV(k0,thi,ep1,ep2,d)*exp(2*1j*d*k1zi(k0,thi,ep1))*(k0z(k0,th) + k1z(k0,th,ep1))*sqrt(ep1)*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + k1zi(k0,thi,ep1)*ep1)*sqrt(ep2) + \
             bb0VV(k0,thi,ep1,ep2,d)*sqrt(ep1)*((k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) - k1zi(k0,thi,ep1)*ep1) + exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1)*(k1zi(k0,thi,ep1)**2 + kir(k0,thi)**2) + k1zi(k0,thi,ep1)*ep1))*sqrt(ep2) + \
             c0VV(k0,thi,ep1,ep2,d)*exp(1j*d*(k1zi(k0,thi,ep1) + k2zi(k0,thi,ep2)))*ep1*(exp(2*1j*d*k1z(k0,th,ep1))*(-k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2) - k2zi(k0,thi,ep2)*ep2) - (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1)*(k2zi(k0,thi,ep2)**2 + kir(k0,thi)**2) + k2zi(k0,thi,ep2)*ep2))))/\
             (exp(1j*d*(k1zi(k0,thi,ep1) + k2z(k0,th,ep2)))*(exp(2*1j*d*k1z(k0,th,ep1))*(k0z(k0,th) - k1z(k0,th,ep1))*(k1z(k0,th,ep1) - k2z(k0,th,ep2)) + (k0z(k0,th) + k1z(k0,th,ep1))*(k1z(k0,th,ep1) + k2z(k0,th,ep2)))*kir(k0,thi)*(kx(k0,th,ph)**2 + ky(k0,th,ph)**2)*ep1*sqrt(ep2))

"""<h2> Sección Eficaz </h2>
<br>

**A orden uno es la ecuación (27) del paper de Moghaddam:
falta escribir bien la correlación entre f1 y f2 - que yo puse gaussiana**
"""

## Espectro de potencias de la superficie ##
# gaussiana

import numpy as np

def w(acf,s,l,k1,k2):
  
  if(acf==1):  
    # gaussiana
    return s**2*l**2/(4*np.pi)*np.exp(-0.25*l**2*(k1**2+k2**2))
  
  if(acf==2):
    # exponencial
    return s**2*l**2/(2*np.pi*(1+(k1**2+k2**2)*l**2)**(3/2))

  if(acf==3):
    # power law
    return s**2*l**2/(2*np.pi)*np.exp(-np.sqrt(k1**2+k2**2)*l)

  else:
    return print('ACF invalida')


# correlación entre las superficies

def w_f1f2(s1,l1,s2,l2,k1,k2):
    return 0*s1*s2*l1*l2/(4*np.pi)*np.exp(-0.125*(l1**2+l2**2)*(k1**2+k2**2))

# def W_f1f2(s1,s2,l1,l2,k1,k2):
#     return s1*s2*l1*l2/(4*np.pi**2*(1+l1**2*(k1**2+k2**2))**(3/4)*(1+l2**2*(k1**2+k2**2))**(3/4))

"""**Secciones eficaces a orden uno para los cuatro canales**"""

# CANAL HH #
def S01HH(k0,thi,phi,th,ph,ep1,ep2,d,s1,l1,s2,l2,k1,k2,acf):
    return 4*np.pi*k0**2*cos(th)**2*(abs(a1HHF1(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s1,l1,k1,k2)+\
            abs(a1HHF2(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s2,l2,k1,k2)+\
            2*real(a1HHF1(k0,thi,phi,th,ph,ep1,ep2,d)*conj(a1HHF2(k0,thi,phi,th,ph,ep1,ep2,d)))*w_f1f2(s1,l1,s2,l2,k1,k2))
# CANAL VH #
def S01VH(k0,thi,phi,th,ph,ep1,ep2,d,s1,l1,s2,l2,k1,k2,acf):
    return 4*np.pi*k0**2*cos(th)**2*(abs(a1VHF1(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s1,l1,k1,k2)+\
            abs(a1VHF2(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s2,l2,k1,k2)+\
            2*real(a1VHF1(k0,thi,phi,th,ph,ep1,ep2,d)*conj(a1VHF2(k0,thi,phi,th,ph,ep1,ep2,d)))*w_f1f2(s1,l1,s2,l2,k1,k2))

# CANAL VV #
def S01VV(k0,thi,phi,th,ph,ep1,ep2,d,s1,l1,s2,l2,k1,k2,acf):
    return 4*np.pi*k0**2*cos(th)**2*(abs(a1VVF1(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s1,l1,k1,k2)+\
            abs(a1VVF2(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s2,l2,k1,k2)+\
            2*real(a1VVF1(k0,thi,phi,th,ph,ep1,ep2,d)*conj(a1VVF2(k0,thi,phi,th,ph,ep1,ep2,d)))*w_f1f2(s1,l1,s2,l2,k1,k2))

# CANAL HV #
def S01HV(k0,thi,phi,th,ph,ep1,ep2,d,s1,l1,s2,l2,k1,k2,acf):
    return 4*np.pi*k0**2*cos(th)**2*(abs(a1HVF1(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s1,l1,k1,k2)+\
            abs(a1HVF2(k0,thi,phi,th,ph,ep1,ep2,d))**2*w(acf,s2,l2,k1,k2)+\
            2*real(a1HVF1(k0,thi,phi,th,ph,ep1,ep2,d)*conj(a1HVF2(k0,thi,phi,th,ph,ep1,ep2,d)))*w_f1f2(s1,l1,s2,l2,k1,k2))